---
apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: Workspace
metadata:
  annotations:
    kommander.mesosphere.io/display-name: Lazarus Workspace
    workspace.kommander.mesosphere.io/allow-existing-namespace: "true"
  labels:
    caren.nutanix.com/namespace-sync: ""
    workspaces.kommander.mesosphere.io/can-use-global-infrastructure-provider: "true"
  generateName: lazarus-cluster-
spec:
  namespaceName: lazarus-workspace