apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lazarus-cluster
  namespace: kommander
spec:
  dependsOn:
  - name: lazarus-workspace
    namespace: kommander
  interval: 5s
  path: ./kustomizations/clusters
  prune: true
  sourceRef:
   kind: GitRepository
   name: lazarus-gitops
   namespace: kommander