#THIS IS THE CRS DEFINATION FILE THAT GETS APPLIED TO THE MANAGEMENT CLUSTER
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: lazarus-crs
  namespace: lazarus-workspace
spec:
  strategy: Reconcile
  clusterSelector:
    matchLabels:
      #This has to match the actual cluster name.
      konvoy.d2iq.io/cluster-name: lazarus
  resources:
    - kind: ConfigMap
      name: lazarus-crs-configmap