apiVersion: v1
data:
  credentials: W3sidHlwZSI6ImJhc2ljX2F1dGgiLCJkYXRhIjp7InByaXNtQ2VudHJhbCI6eyJ1c2VybmFtZSI6InRlc3QiLCJwYXNzd29yZCI6InRlc3QifX19XSIK
kind: Secret
metadata:
  finalizers:
  - nutanixcluster/infrastructure.cluster.x-k8s.io
  labels:
    cluster.x-k8s.io/provider: nutanix
  name: lazarus-workload-pc-credentials
  namespace: lazarus-workspace
type: Opaque