#THIS IS THE CONFIGMAP THAT IS APPLIED TO THE MANAGEMENT CLUSTER FOR CRS 
apiVersion: v1
kind: ConfigMap
metadata:
  name: lazarus-crs-configmap
  namespace: lazarus-workspace  
data:
  #BELOW IS WHAT GETS PROPROGATED TO THE WORKLOAD CLUSTER
  git-repository.yaml: |
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: lazarus-gitops
      namespace: lazarus-workspace
    spec:
      interval: 1m0s
      url: https://github.com/WinsonSou/lazarus-cluster-gitops-pro.git
      ref:
        branch: main
  kustomization.yaml: |
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: lazarus-gitops
      namespace: lazarus-workspace
    spec:
      interval: 10m0s
      path: ./resources/workspaces/lazarus/cluster/namespaces
      prune: true
      sourceRef:
        kind: GitRepository
        name: lazarus-gitops